version: '2'
services:
    fleetmanagement-app:
        image: fleetmanagement
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://fleetmanagement-mysql:3306/fleetmanagement?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    fleetmanagement-mysql:
        extends:
            file: mysql.yml
            service: fleetmanagement-mysql
